/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.resume.panel;

import com.mycompany.entity.User;
import com.mycompany.resume.main.Config;

/**
 *
 * @author Asus
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ProfilePanel() {
        initComponents();
    }

    public void fillUserComponents() {
        txtAreaProfileDescription.setText(Config.loggedInUser.getProfileDescription());
    }

    public void fillUser(User user) {
        String profileDescription = txtAreaProfileDescription.getText();
        user.setProfileDescription(profileDescription);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProfile = new javax.swing.JScrollPane();
        txtAreaProfileDescription = new javax.swing.JTextArea();

        txtAreaProfileDescription.setColumns(20);
        txtAreaProfileDescription.setRows(5);
        panelProfile.setViewportView(txtAreaProfileDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane panelProfile;
    private javax.swing.JTextArea txtAreaProfileDescription;
    // End of variables declaration//GEN-END:variables
}
